### ISSUE TITLE
3rd party libs in amd/src/ still included in precheck

### ISSUE THREAD

**Issue by mudrd8mz** [Behaviour-Analytics/moodle-block_lord#1]
![image](https://user-images.githubusercontent.com/85831/101884461-04b5f200-3b99-11eb-8839-ca6d6f4c1f13.png)

Many of these are caused by the fact that files like amd/src/d3.js are still being checked. If they were also included in the thirdpartylibs.xml file (as they should), you would get much more realistic results.

**Comment by tedkrahn** [comment]
Thanks for the information, this has now been done. Prechecks look much better.
